### ISSUE TITLE
Update to libfido2 version 1.5.0_1

### ISSUE THREAD

**Issue by Blobonat** [keys-pub/go-libfido2#15]
The current go module requires libfido2 version 1.4.0_2, but version 1.5.0_1 is available.

**Comment by mskonovalov** [comment]
I think it is already updated in this PR https://github.com/keys-pub/go-libfido2/pull/12
but for some reason if you do
`go get  go get github.com/keys-pub/go-libfido2 ` it installs version 1.4.0 while the latest should be 1.5.0
But ` go get github.com/keys-pub/go-libfido2@1.5.0` doesn't work

To fix this you need to `go get github.com/keys-pub/go-libfido2@8e225f5` which will install version `1.4.1` which is weird but works
🤷

**Comment by gabriel** [comment]
I made a new tag/release. 

`go get -u github.com/keys-pub/go-libfido2` should install latest (1.5.1).
If you `go get github.com/keys-pub/go-libfido2@84cd535d` (the latest commit, it should show 1.5.1).

I think I might have messed up the tags and removed them but the GOPROXY remembered?

**Comment by mskonovalov** [comment]
Thanks, this solves the issue
