### ISSUE TITLE
AuthData is incorrect

### ISSUE THREAD

**Issue by mskonovalov** [keys-pub/go-libfido2#17]
Hi @gabriel,

I'm not sure if I should ask here but:

I'm trying to implement WebAuthn with Okta and Yubikey device in GoLang (client side)
I have working implementation in Python that uses https://developers.yubico.com/python-fido2/

But my implementation with go-libfido2 doesn't work.

I call `device.Assertion(...)` and for some reason length of the Authenticator data is always 39 (which I guess is incorrect).
For some reason flag bite has flags bit 6 that means that cred data is included but the length of it only 2 bites 
So if I try to call https://github.com/fxamacker/webauthn/blob/master/common.go#L40 as a verification (not really sure if this implementation is reliable) it fails because it assumes that if credentialDataIncluded then it should be at least 18 bytes long (also not sure if it is a correct assumption or not)

**Comment by mskonovalov** [comment]
I enabled debug logging from the libfido2 and it shows:
```
cbor_decode_assert_authdata: buf=0xd5081f0, len=37
```

While in GoLang I get byte array of 39 bytes.
There seems to be the issue

**Comment by gabriel** [comment]
Thanks for reporting the issue, I'll take a look at it tomorrow.

**Comment by gabriel** [comment]
So this library calls libfido2 `fido_dev_get_assert` and `fido_assert_authdata_ptr` to get the authdata and it looks like it is returning 39 bytes. 

I also checked the libfido2 [fido2-assert tool](https://github.com/Yubico/libfido2/blob/master/tools/assert_get.c#L176) output of authdata and it also outputs 39 bytes, so I think this is a lower level issue in libfido2 itself?

You can try posting an issue there?

If you need help building libfido2 and running the fido2-assert tool directly lmk.

**Comment by mskonovalov** [comment]
Thanks for taking a look.
Did you try to enable the debug logging for the tool? Did it print the size of the data as 37?
I actually was able somehow to build libfido2 from sources and added some debug logging into it. But not sure how to debug further yet.

**Comment by gabriel** [comment]
Yeah I saw it as 37 bytes on FIDO_DEBUG too, not sure why the data comes out as 39 bytes on fido_assert_authdata_len.

**Comment by mskonovalov** [comment]
Ok, let me report this issue to the libfido2

**Comment by mskonovalov** [comment]
Could you pls verify on the different versions of libfido2? Might that be related to the recent changes?

**Comment by mskonovalov** [comment]
https://github.com/Yubico/libfido2/issues/241

**Comment by gabriel** [comment]
I renamed AuthData to AuthDataCBOR to avoid confusion and to allow us to add AuthData in the future.

**Comment by mskonovalov** [comment]
Thanks
