### ISSUE TITLE
Does not compile with Go 1.16

### ISSUE THREAD

**Issue by rgl** [keys-pub/go-libfido2#23]
When using Go 1.16, the line at https://github.com/keys-pub/go-libfido2/blob/51981ad278cd016feb4ff07c5af2512f2d92105a/examples_test.go#L158

Fails with:

```
# go-libfido2-example
./main.go:62:11: cannot use [][]byte{...} (type [][]byte) as type []byte in argument to device.Assertion
```

After removing the cast, it compiled as:

```go
	assertion, err := device.Assertion(
		"keys.pub",
		cdh,
		attest.CredentialID, // was [][]byte{attest.CredentialID},
		pin,
		&libfido2.AssertionOpts{
			Extensions: []libfido2.Extension{libfido2.HMACSecretExtension},
			UP:         libfido2.True,
			HMACSalt:   salt,
		},
	)
```

I'm using the libfido2-dev:amd64 1.6.0~ppa~focal1 ubuntu package (from the ppa:yubico/stable repository).

**Comment by mskonovalov** [comment]
I suspect it is not GoLang version
it is not cast - it is creating two-dimensional array from single dimension array.

So you need to check what is the signature of the function: 
`attest.CredentialID` - is a single dimension array that represents single Credential ID
but the function accepts a list of Credential IDs represented by array of arrays (or two-dimensional array)

**Comment by mskonovalov** [comment]
Also i switched to GoLang 1.16 and it all compiles without issues

**Comment by gabriel** [comment]
I changed that method to take an array of CredentialID's to match the API, which is why you might have encountered this.
