### ISSUE TITLE
Bump version for `go get` to pull the latest version

### ISSUE THREAD

**Issue by prateeknischal** [keys-pub/go-libfido2#36]
Would it be possible to bump the version for `go get` to pick up the current state. go-libfido2@v1.5.2 has the Mac builds broken due to incorrect paths for openssl which were fixed in the current master. 

Right now, I am only able to build it by either `replace`ing the go-libfido2 dependency in go.mod or having to pull `go get github.com/keys-pub/go-libfido2@master`.

**Comment by gabriel** [comment]
Published v1.5.3
